### ISSUE TITLE
Step 5.2.5 of Tutorial Marked Graph does not work

### ISSUE THREAD

**Issue by valdemarneto** [diverse-project/k3#40]
Hi all.

I am running your tutorial of Marked Graph using Windows 7, Java 8, GEMOC Studio 2.0.1.
I had already runned it and it worked in a precendent version of your studio (before 2.0, I think).

However, this step does not work:

5.2.5. Add the Animation service

Right click on "MarkedGraphViewpoint" to select "New Extension / Java Extension".
Set "Qualified Class Name" to "org.gemoc.sample.markedgraph.animation.services.MarkedgraphAnimationServices".
In the project, org.gemoc.sample.markedgraph.animation project, in src/org.gemoc.sample.markedgraph.animation.services, copy the MarkedgraphDebugServices.java file to MarkedgraphAnimationServices.java. Then, change AbstractGemocDebuggerServices to AbstractGemocAnimatorServices in its source code (two times: import and extends). Finally, change "Debug" to "Animation".

When I go to the workspace, there is no the mentioned class there (MarkedgraphDebugServices). I did not find it. 

It is weird because I already runned this tutorial and worked. But, in this new version of GEMOC, I am not obtaining success.

Additionally, when I am creating the DSE in step 4.2.1, when I click to finish the creation as a debug representation, the following errors happen:

Stream closed
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.Reader.read(Unknown Source)
	at org.gemoc.xdsmlframework.extensions.sirius.command.AddDebugLayerHandler.getContent(AddDebugLayerHandler.java:764)
	at org.gemoc.xdsmlframework.extensions.sirius.command.AddDebugLayerHandler.createServiceClass(AddDebugLayerHandler.java:720)
	at org.gemoc.xdsmlframework.extensions.sirius.command.AddDebugLayerHandler.getOrCreateServiceClass(AddDebugLayerHandler.java:683)
	at org.gemoc.xdsmlframework.extensions.sirius.wizards.NewGemocDebugRepresentationWizard$FinishRunnable.run(NewGemocDebugRepresentationWizard.java:120)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:466)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:374)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1059)
	at org.gemoc.xdsmlframework.extensions.sirius.wizards.NewGemocDebugRepresentationWizard.performFinish(NewGemocDebugRepresentationWizard.java:350)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:853)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:438)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:269)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:290)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:159)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

I am following and running the tutorial step-by-step. If you are interested, I can send the file where I am taking notes about the differences between what is recommended in the tutorial and what is currently available to work in GEMOC 2.0.1.

Regards,
Valdemar.

**Comment by dvojtise** [comment]
Hi thanks for the feedback :smiley: 
However this isn't an issue for K3 but for GEMOC and its components. So this issue should be reported to one of the GEMOC issue tracker either on its origin gforge host project (https://gforge.inria.fr/projects/gemoc-dev/) or on one of the GEMOC repositories on github. in that case either the general Studio (https://github.com/gemoc/gemoc-studio) would be fine or better in the repo with thecomponent that is impacted. In that case https://github.com/gemoc/modelanimation

but I agree we still don't have any web page to clearly indicate to end users where to post issues

**Comment by dvojtise** [comment]
This issue was moved to gemoc/modelanimation#3
